// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YardimMasasi.VeriErisim;

#nullable disable

namespace YardimMasasi.VeriErisim.Migrations
{
    [DbContext(typeof(YardimMasasiContext))]
    [Migration("20230506112609_isimlendirmeDegisikligi20230506")]
    partial class isimlendirmeDegisikligi20230506
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YardimMasasi.Nesneler.AltKonuNesneler.Db.AltKonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnaKonuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SurecTanimiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnaKonuId");

                    b.HasIndex("SurecTanimiId");

                    b.ToTable("AltKonular");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.AnaKonuNesneler.Db.AnaKonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AnaKonular");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.BirimNesneler.Db.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.EkipNesneler.Db.Ekip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Ekipler");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AltKonuId")
                        .HasColumnType("int");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OluşturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SonİslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalepSahibiId")
                        .HasColumnType("int");

                    b.Property<int>("TeknisyenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.GorevIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Acıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<int>("HedefKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IslemTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("GorevIslem");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.GorevMesaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<int>("HedefKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MesajTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesajTuru")
                        .HasColumnType("int");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("GorevMesaj");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.EkipAltKonu", b =>
                {
                    b.Property<int>("AltKonuId")
                        .HasColumnType("int");

                    b.Property<int>("EkipId")
                        .HasColumnType("int");

                    b.HasKey("AltKonuId", "EkipId");

                    b.HasIndex("EkipId");

                    b.ToTable("EkipAltKonular");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.Surec", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("SurecTanimiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurecTanimiId");

                    b.ToTable("Surecler");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecAdimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AktifAdim")
                        .HasColumnType("bit");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("SurecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("SurecId");

                    b.ToTable("SurecAdimi");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecAdimiTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("SurecTanimiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("SurecTanimiId");

                    b.ToTable("SurecAdimiTanimi");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurecTanimlari");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.AltKonuNesneler.Db.AltKonu", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.AnaKonuNesneler.Db.AnaKonu", "AnaKonu")
                        .WithMany("AltKonular")
                        .HasForeignKey("AnaKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YardimMasasi.Nesneler.SurecNesneler.Db.SurecTanimi", "SurecTanimi")
                        .WithMany("AltKonular")
                        .HasForeignKey("SurecTanimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaKonu");

                    b.Navigation("SurecTanimi");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.EkipNesneler.Db.Ekip", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.BirimNesneler.Db.Birim", "Birim")
                        .WithMany("Ekipler")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.GorevIslem", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.GorevNesneler.Db.Gorev", "Gorev")
                        .WithMany("Islemler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.GorevMesaj", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.GorevNesneler.Db.Gorev", "Gorev")
                        .WithMany("Mesajlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.EkipAltKonu", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.AltKonuNesneler.Db.AltKonu", "AltKonu")
                        .WithMany("Ekipler")
                        .HasForeignKey("AltKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YardimMasasi.Nesneler.EkipNesneler.Db.Ekip", "Ekip")
                        .WithMany("AltKonular")
                        .HasForeignKey("EkipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AltKonu");

                    b.Navigation("Ekip");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.Surec", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.GorevNesneler.Db.Gorev", "Gorev")
                        .WithOne("Surec")
                        .HasForeignKey("YardimMasasi.Nesneler.SurecNesneler.Db.Surec", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YardimMasasi.Nesneler.SurecNesneler.Db.SurecTanimi", "SurecTanimi")
                        .WithMany("Surecler")
                        .HasForeignKey("SurecTanimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("SurecTanimi");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecAdimi", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.BirimNesneler.Db.Birim", "Birim")
                        .WithMany("SurecAdimlari")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YardimMasasi.Nesneler.SurecNesneler.Db.Surec", "Surec")
                        .WithMany("SurecAdimlari")
                        .HasForeignKey("SurecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Surec");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecAdimiTanimi", b =>
                {
                    b.HasOne("YardimMasasi.Nesneler.BirimNesneler.Db.Birim", "Birim")
                        .WithMany("SurecAdimTanimlari")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YardimMasasi.Nesneler.SurecNesneler.Db.SurecTanimi", "SurecTanimi")
                        .WithMany("SurecAdimlari")
                        .HasForeignKey("SurecTanimiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("SurecTanimi");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.AltKonuNesneler.Db.AltKonu", b =>
                {
                    b.Navigation("Ekipler");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.AnaKonuNesneler.Db.AnaKonu", b =>
                {
                    b.Navigation("AltKonular");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.BirimNesneler.Db.Birim", b =>
                {
                    b.Navigation("Ekipler");

                    b.Navigation("SurecAdimTanimlari");

                    b.Navigation("SurecAdimlari");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.EkipNesneler.Db.Ekip", b =>
                {
                    b.Navigation("AltKonular");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.GorevNesneler.Db.Gorev", b =>
                {
                    b.Navigation("Islemler");

                    b.Navigation("Mesajlar");

                    b.Navigation("Surec")
                        .IsRequired();
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.Surec", b =>
                {
                    b.Navigation("SurecAdimlari");
                });

            modelBuilder.Entity("YardimMasasi.Nesneler.SurecNesneler.Db.SurecTanimi", b =>
                {
                    b.Navigation("AltKonular");

                    b.Navigation("SurecAdimlari");

                    b.Navigation("Surecler");
                });
#pragma warning restore 612, 618
        }
    }
}
